# Ingress routes
filegroup(
    name = "routes",
    srcs = [
        "routes.yaml",
    ],
    visibility = ["//visibility:public"],
)

# TLS configuration
filegroup(
    name = "tls",
    srcs = [
        "tls.yaml",
    ],
    visibility = ["//visibility:public"],
) 