// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BadgerServiceClient is the client API for BadgerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BadgerServiceClient interface {
	// Job management
	StartJob(ctx context.Context, in *StartJobRequest, opts ...grpc.CallOption) (*StartJobResponse, error)
	GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error)
	ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error)
	// Node management
	PowerOnNode(ctx context.Context, in *NodeControlRequest, opts ...grpc.CallOption) (*NodeControlResponse, error)
	PowerOffNode(ctx context.Context, in *NodeControlRequest, opts ...grpc.CallOption) (*NodeControlResponse, error)
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
}

type badgerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBadgerServiceClient(cc grpc.ClientConnInterface) BadgerServiceClient {
	return &badgerServiceClient{cc}
}

func (c *badgerServiceClient) StartJob(ctx context.Context, in *StartJobRequest, opts ...grpc.CallOption) (*StartJobResponse, error) {
	out := new(StartJobResponse)
	err := c.cc.Invoke(ctx, "/api.BadgerService/StartJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *badgerServiceClient) GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error) {
	out := new(GetJobStatusResponse)
	err := c.cc.Invoke(ctx, "/api.BadgerService/GetJobStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *badgerServiceClient) ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, "/api.BadgerService/ListJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *badgerServiceClient) PowerOnNode(ctx context.Context, in *NodeControlRequest, opts ...grpc.CallOption) (*NodeControlResponse, error) {
	out := new(NodeControlResponse)
	err := c.cc.Invoke(ctx, "/api.BadgerService/PowerOnNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *badgerServiceClient) PowerOffNode(ctx context.Context, in *NodeControlRequest, opts ...grpc.CallOption) (*NodeControlResponse, error) {
	out := new(NodeControlResponse)
	err := c.cc.Invoke(ctx, "/api.BadgerService/PowerOffNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *badgerServiceClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, "/api.BadgerService/ListNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BadgerServiceServer is the server API for BadgerService service.
// All implementations must embed UnimplementedBadgerServiceServer
// for forward compatibility
type BadgerServiceServer interface {
	// Job management
	StartJob(context.Context, *StartJobRequest) (*StartJobResponse, error)
	GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error)
	ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error)
	// Node management
	PowerOnNode(context.Context, *NodeControlRequest) (*NodeControlResponse, error)
	PowerOffNode(context.Context, *NodeControlRequest) (*NodeControlResponse, error)
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	mustEmbedUnimplementedBadgerServiceServer()
}

// UnimplementedBadgerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBadgerServiceServer struct {
}

func (UnimplementedBadgerServiceServer) StartJob(context.Context, *StartJobRequest) (*StartJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartJob not implemented")
}
func (UnimplementedBadgerServiceServer) GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobStatus not implemented")
}
func (UnimplementedBadgerServiceServer) ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedBadgerServiceServer) PowerOnNode(context.Context, *NodeControlRequest) (*NodeControlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PowerOnNode not implemented")
}
func (UnimplementedBadgerServiceServer) PowerOffNode(context.Context, *NodeControlRequest) (*NodeControlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PowerOffNode not implemented")
}
func (UnimplementedBadgerServiceServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedBadgerServiceServer) mustEmbedUnimplementedBadgerServiceServer() {}

// UnsafeBadgerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BadgerServiceServer will
// result in compilation errors.
type UnsafeBadgerServiceServer interface {
	mustEmbedUnimplementedBadgerServiceServer()
}

func RegisterBadgerServiceServer(s grpc.ServiceRegistrar, srv BadgerServiceServer) {
	s.RegisterService(&BadgerService_ServiceDesc, srv)
}

func _BadgerService_StartJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BadgerServiceServer).StartJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BadgerService/StartJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BadgerServiceServer).StartJob(ctx, req.(*StartJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BadgerService_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BadgerServiceServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BadgerService/GetJobStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BadgerServiceServer).GetJobStatus(ctx, req.(*GetJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BadgerService_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BadgerServiceServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BadgerService/ListJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BadgerServiceServer).ListJobs(ctx, req.(*ListJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BadgerService_PowerOnNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BadgerServiceServer).PowerOnNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BadgerService/PowerOnNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BadgerServiceServer).PowerOnNode(ctx, req.(*NodeControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BadgerService_PowerOffNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BadgerServiceServer).PowerOffNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BadgerService/PowerOffNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BadgerServiceServer).PowerOffNode(ctx, req.(*NodeControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BadgerService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BadgerServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BadgerService/ListNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BadgerServiceServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BadgerService_ServiceDesc is the grpc.ServiceDesc for BadgerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BadgerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.BadgerService",
	HandlerType: (*BadgerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartJob",
			Handler:    _BadgerService_StartJob_Handler,
		},
		{
			MethodName: "GetJobStatus",
			Handler:    _BadgerService_GetJobStatus_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _BadgerService_ListJobs_Handler,
		},
		{
			MethodName: "PowerOnNode",
			Handler:    _BadgerService_PowerOnNode_Handler,
		},
		{
			MethodName: "PowerOffNode",
			Handler:    _BadgerService_PowerOffNode_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _BadgerService_ListNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

// OvermindServiceClient is the client API for OvermindService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OvermindServiceClient interface {
	// Job orchestration
	ExecuteJob(ctx context.Context, in *Job, opts ...grpc.CallOption) (*Job, error)
	CancelJob(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error)
	GetJobDetails(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error)
	// Cluster management
	GetClusterStatus(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
}

type overmindServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOvermindServiceClient(cc grpc.ClientConnInterface) OvermindServiceClient {
	return &overmindServiceClient{cc}
}

func (c *overmindServiceClient) ExecuteJob(ctx context.Context, in *Job, opts ...grpc.CallOption) (*Job, error) {
	out := new(Job)
	err := c.cc.Invoke(ctx, "/api.OvermindService/ExecuteJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *overmindServiceClient) CancelJob(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error) {
	out := new(GetJobStatusResponse)
	err := c.cc.Invoke(ctx, "/api.OvermindService/CancelJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *overmindServiceClient) GetJobDetails(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error) {
	out := new(GetJobStatusResponse)
	err := c.cc.Invoke(ctx, "/api.OvermindService/GetJobDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *overmindServiceClient) GetClusterStatus(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, "/api.OvermindService/GetClusterStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OvermindServiceServer is the server API for OvermindService service.
// All implementations must embed UnimplementedOvermindServiceServer
// for forward compatibility
type OvermindServiceServer interface {
	// Job orchestration
	ExecuteJob(context.Context, *Job) (*Job, error)
	CancelJob(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error)
	GetJobDetails(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error)
	// Cluster management
	GetClusterStatus(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	mustEmbedUnimplementedOvermindServiceServer()
}

// UnimplementedOvermindServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOvermindServiceServer struct {
}

func (UnimplementedOvermindServiceServer) ExecuteJob(context.Context, *Job) (*Job, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteJob not implemented")
}
func (UnimplementedOvermindServiceServer) CancelJob(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelJob not implemented")
}
func (UnimplementedOvermindServiceServer) GetJobDetails(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobDetails not implemented")
}
func (UnimplementedOvermindServiceServer) GetClusterStatus(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterStatus not implemented")
}
func (UnimplementedOvermindServiceServer) mustEmbedUnimplementedOvermindServiceServer() {}

// UnsafeOvermindServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OvermindServiceServer will
// result in compilation errors.
type UnsafeOvermindServiceServer interface {
	mustEmbedUnimplementedOvermindServiceServer()
}

func RegisterOvermindServiceServer(s grpc.ServiceRegistrar, srv OvermindServiceServer) {
	s.RegisterService(&OvermindService_ServiceDesc, srv)
}

func _OvermindService_ExecuteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Job)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OvermindServiceServer).ExecuteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.OvermindService/ExecuteJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OvermindServiceServer).ExecuteJob(ctx, req.(*Job))
	}
	return interceptor(ctx, in, info, handler)
}

func _OvermindService_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OvermindServiceServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.OvermindService/CancelJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OvermindServiceServer).CancelJob(ctx, req.(*GetJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OvermindService_GetJobDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OvermindServiceServer).GetJobDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.OvermindService/GetJobDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OvermindServiceServer).GetJobDetails(ctx, req.(*GetJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OvermindService_GetClusterStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OvermindServiceServer).GetClusterStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.OvermindService/GetClusterStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OvermindServiceServer).GetClusterStatus(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OvermindService_ServiceDesc is the grpc.ServiceDesc for OvermindService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OvermindService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.OvermindService",
	HandlerType: (*OvermindServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteJob",
			Handler:    _OvermindService_ExecuteJob_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _OvermindService_CancelJob_Handler,
		},
		{
			MethodName: "GetJobDetails",
			Handler:    _OvermindService_GetJobDetails_Handler,
		},
		{
			MethodName: "GetClusterStatus",
			Handler:    _OvermindService_GetClusterStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
